### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by fletchercr**
First development version of eggd_MetricsOutput_MultiQC_parser

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/1)

### CODE REVIEW

**Review by Arun-bioinformatics — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/1)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @fletchercr)

___
*[`resources/home/dnanexus/edit_MetricsOutput.py` line 11 at r1](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/1#-O1Qwe4FD6y3KyqVtrU0:-O1Qwe4FD6y3KyqVtrU1:b-tghyfi) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/65de5bfb6dbf035d463d5f7b7a119f863ad1f09c/resources/home/dnanexus/edit_MetricsOutput.py#L11)):*
> ```Python
> # does this go here as global variables?
> dna_output_filename = "MetricsOutput_MultiQC_DNA.tsv"
> rna_output_filename = "MetricsOutput_MultiQC_RNA.tsv"
> ```

Since these variables are only used in a single function "df_to_tsv" which is called within the main, you could treat these as local variables of "df_to_tsv()" function.



_Code quote:_
```Python
dna_output_filename = "MetricsOutput_MultiQC_DNA.tsv"
rna_output_filename = "MetricsOutput_MultiQC_RNA.tsv"
```
___
*[`resources/home/dnanexus/edit_MetricsOutput.py` line 21 at r1](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/1#-O1Qxi-m8sCCiwrmabty:-O1Qxi-m8sCCiwrmabtz:brjvc8u) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/65de5bfb6dbf035d463d5f7b7a119f863ad1f09c/resources/home/dnanexus/edit_MetricsOutput.py#L21)):*
> ```Python
>     Parameters
>     ----------
>     input_file : file
> ```

change "file" to "str", then specify that the string is filepath of the "Metricsoutput.tsv"



_Code quote:_
```Python
file
```
___
*[`resources/home/dnanexus/edit_MetricsOutput.py` line 157 at r1](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/1#-O1R2LLcDVjI_4OwQSba:-O1R2LLcDVjI_4OwQSbb:b-8ck1n3) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/65de5bfb6dbf035d463d5f7b7a119f863ad1f09c/resources/home/dnanexus/edit_MetricsOutput.py#L157)):*
> ```Python
>     transposed_df['CONTAMINATION_SUMMARY'] = None
>     # for samples without NaN values, populate CONTAMINATION_SUMMARY with the opposite of filters bool
>     transposed_df.loc[~nan_values, 'CONTAMINATION_SUMMARY'] = ~filters[~nan_values]
> ```

This line works really well, but both comment and line of code was a bit hard to understand. Could be clarified if you avoid the double negative  i.e. "for samples without NaN values" to "for samples with contamination-related values".
You can also expand on how does the CONTAMINATION_SUMMARY column should be populated, e.g.:
RNA sample = None
DNA sample with contamination below threshold = True
DNA sample with contamination above threshold = False

**Comment by Arun-bioinformatics** [comment]
Comments addressed in https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/pull/3

**Review by Arun-bioinformatics — APPROVED** [review]
> Reviewed 11 of 13 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fletchercr)

**Review by nadia31415 — CHANGES_REQUESTED** [review]
some PEP 8 comments to address

> Reviewed 10 of 13 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/1#-:-O2-m_LKCz-H-zO9rI4_:b-wk94c9)* status: all files reviewed, 2 unresolved discussions (waiting on @fletchercr)

___
*[`resources/home/dnanexus/edit_MetricsOutput.py` line 25 at r3](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/1#-O2-k1x311cO_5CYG_rd:-O2-k1x417Ix3B6Prd2K:b-wjd3qx) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/cf107041e51d1d1cdb1d62ba477f9afd5fea99aa/resources/home/dnanexus/edit_MetricsOutput.py#L25)):*
> ```Python
>         modified dataframe
>     """
>     with open(input_file, "r", encoding="UTF-8") as file:
> ```

Since this function is quite big, you might want to add error handling in this function to make sure files are read in etc.. , I think error handling might be useful in other functions e.g edit_column_headers function



_Code quote:_
```Python
with open(input_fil
```
___
*[`resources/home/dnanexus/packages/argparse-1.4.0-py2.py3-none-any.whl` line 0 at r3](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/1#-O2-ko56EQDT-33lSZbR:-O2-ko56EQDT-33lSZbS:b-vdjbhs) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/cf107041e51d1d1cdb1d62ba477f9afd5fea99aa/resources/home/dnanexus/packages/argparse-1.4.0-py2.py3-none-any.whl#L0)):*
Some of these .whl files (or maybe any) may not be needed, we have package bundles in 001 reference and in the dxapp.json, you can have a app depending on assets in the runspec field (here's an example https://github.com/eastgenomics/eggd_tandem_hunter/blob/main/dxapp.json#L77)

**Review by nadia31415 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/1)* status: all files reviewed, 3 unresolved discussions (waiting on @fletchercr)

___
*[`src/code.sh` line 18 at r3](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/1#-O2-n4mE--yCQId6O4FT:-O2-n4mE--yCQId6O4FU:b-v9ue65) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/blob/cf107041e51d1d1cdb1d62ba477f9afd5fea99aa/src/code.sh#L18)):*
> ```Shell
> 
>     # Install all python packages from this app
>     sudo -H python3 -m pip install --no-index --no-deps packages/*
> ```

why was sudo needed here?

**Review by nadia31415 — APPROVED** [review]
Corrections from PR4 - https://github.com/eastgenomics/eggd_MetricsOutput_MultiQC_parser/pull/4 have been incorporated into this PR

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_MultiQC_parser/1#-:-O5liNrhBV1VfqmP78Is:b8maib7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fletchercr)

**Pull request merged**
